### ISSUE TITLE
Homebrew Support

### ISSUE THREAD

**Issue by nebhale** [tpope/rbenv-aliases#4]
Currently, cloning the repo is the only way to install this plugin.  It'd be quite nice if you could also install it using [Homebrew](http://mxcl.github.io/homebrew/).  I suspect that the pattern has been set by the [`ruby-build`](https://github.com/sstephenson/ruby-build) project and it's [Homebrew formula](https://github.com/mxcl/homebrew/blob/master/Library/Formula/ruby-build.rb).

**Comment by blackjid** [comment]
Hi!, Can you tag the latest version?? i'm missing semantic version aliases support.....
thanks!

**Comment by tpope** [comment]
OK
